# Generated by Django 5.1 on 2024-10-24 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estado',
            field=models.CharField(default='novo', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter 9 dígitos.', regex='^\\d{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'),
        ),
    ]
