# Generated by Django 5.1 on 2024-10-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0002_product_estado_alter_user_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='estado',
        ),
    ]
